export enum ErrorCode {
  BANK_NOT_FOUND = 'BANK_NOT_FOUND',
  CONFIGURATION_NOT_FOUND = 'CONFIGURATION_NOT_FOUND',
  INVALID_CONFIGURATION = 'INVALID_CONFIGURATION',
  INVALID_SERVICE = 'INVALID_SERVICE',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
